# Generated by Django 4.1.5 on 2023-01-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markeurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markeur',
            name='title',
        ),
    ]
